/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as IndexImport } from './routes/index'
import { Route as UsersUserIdImport } from './routes/users/$userId'
import { Route as ExperiencesExperienceIdIndexImport } from './routes/experiences/$experienceId/index'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdRoute = UsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any)

const ExperiencesExperienceIdIndexRoute =
  ExperiencesExperienceIdIndexImport.update({
    id: '/experiences/$experienceId/',
    path: '/experiences/$experienceId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdImport
      parentRoute: typeof rootRoute
    }
    '/experiences/$experienceId/': {
      id: '/experiences/$experienceId/'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/experiences/$experienceId/': typeof ExperiencesExperienceIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/users/$userId' | '/experiences/$experienceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/users/$userId' | '/experiences/$experienceId'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/users/$userId'
    | '/experiences/$experienceId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ExperiencesExperienceIdIndexRoute: typeof ExperiencesExperienceIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ExperiencesExperienceIdIndexRoute: ExperiencesExperienceIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search",
        "/users/$userId",
        "/experiences/$experienceId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.tsx"
    },
    "/experiences/$experienceId/": {
      "filePath": "experiences/$experienceId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
